import { Metadata } from "next";
import Login from "../components/Login";

export const metadata: Metadata = {
  title: "Pagina de Login",
  description: "Generated by create next app",
};

export default function LoginScreen() {
  return (
    <>
      <Login></Login>
    </>
  );
}
