"use client";
import type { Metadata } from "next";
import { ChakraProvider } from "@chakra-ui/react";
import { customTheme } from "./designSystem";

export const metadata: Metadata = {
  title: "My frontend Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body>
        <ChakraProvider theme={customTheme}>{children}</ChakraProvider>
      </body>
    </html>
  );
}
