"use client";
import { ChakraProvider } from "@chakra-ui/react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Footer from "./components/footer";
import HeroSection from "./components/hero-section";
import Navbar from "./components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My frontend Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body>
        <ChakraProvider>
          <Navbar></Navbar>
          <HeroSection></HeroSection>
          <Footer></Footer>
          {children}
        </ChakraProvider>
      </body>
    </html>
  );
}
