import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "My Login Page",
  description: "Generated by create next app",
};

export default function LoginLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <nav>This is the layout for register page</nav>
      <main>{children}</main>
    </>
  );
}
